#!/bin/sh
set -e

# Export all secrets in /run/secrets as uppercase env vars
for secret_file in /run/secrets/*; do
  if [ -f "$secret_file" ]; then
    secret_name=$(basename "$secret_file")
    # transform to uppercase
    env_var_name=$(echo "$secret_name" | tr '[:lower:]' '[:upper:]')
    export "$env_var_name"="$(cat $secret_file)"
  fi
done

exec "$@"
